owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/ramclustr"
homepage_url: "https://rdrr.io/cran/RAMClustR/"
categories:
  - Metabolomics
repositories:
  ramclustr:
    description: "A feature clustering algorithm for non-targeted mass spectrometric metabolomics data using peaks detected using XCMS or using MS1 and MS2 spectra."
    include:
      - ramclustr.xml
      - ramclustr_wrapper.R
      - ramclustr_macros.xml
      - test-data
