owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/recetox-xmsannotator"
homepage_url: "https://github.com/RECETOX/recetox-xMSannotator"
categories:
  - Metabolomics
repositories:
  recetox_xmsannotator_simple:
    description: "Annotate peak table with metabolites"
    include:
      - recetox_xmsannotator_simple.xml
      - macros.xml
  recetox_xmsannotator_advanced:
    description: "Annotate peak table with metabolites"
    include:
      - recetox_xmsannotator_advanced.xml
      - macros.xml
