owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/recetox_aplcms"
homepage_url: "https://github.com/RECETOX/recetox-aplcms"
categories:
  - Metabolomics
description: "Peak detection tool for HRMS profile data."