owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/recetox_aplcms"
homepage_url: "https://github.com/RECETOX/recetox-aplcms"
categories:
  - Metabolomics
repositories:
  recetox_aplcms_align_features:
    description: "apLCMS feature alignment step of LC/MS spectra across samples."
    include:
      - recetox_aplcms_align_features.xml
      - test-data
      - macros.xml
      - utils.R
  recetox_aplcms_compute_clusters:
    description: "apLCMS compute clusters of m/z and RT of individual features."
    include:
      - recetox_aplcms_compute_clusters.xml
      - test-data
      - macros.xml
      - utils.R
  recetox_aplcms_compute_template:
    description: "apLCMS compute template features table."
    include:
      - recetox_aplcms_compute_template.xml
      - test-data
      - macros.xml
      - utils.R
  recetox_aplcms_correct_time:
    description: "apLCMS correction of the RT in each LC/MS profile to achieve better between-profile agreement."
    include:
      - recetox_aplcms_correct_time.xml
      - test-data
      - macros.xml
      - utils.R
  recetox_aplcms_generate_feature_table:
    description: "apLCMS generate feature table from noise-removed LC/MS profile."
    include:
      - recetox_aplcms_generate_feature_table.xml
      - test-data
      - macros.xml
      - utils.R
  recetox_aplcms_merge_known_table:
    description: "apLCMS join knowledge from aligned features and known table."
    include:
      - recetox_aplcms_merge_known_table.xml
      - test-data
      - macros.xml
      - utils.R
  recetox_aplcms_recover_weaker_signals:
    description: "apLCMS weaker signal recovery step after feature alignment."
    include:
      - recetox_aplcms_recover_weaker_signals.xml
      - test-data
      - macros.xml
      - utils.R
      - mzml_id_getter.py
  recetox_aplcms_remove_noise:
    description: "apLCMS filter noise and detect peaks from LC/MS data."
    include:
      - recetox_aplcms_remove_noise.xml
      - test-data
      - macros.xml
      - utils.R
      - mzml_id_getter.py
