owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/recetox_aplcms"
homepage_url: "https://github.com/RECETOX/recetox-aplcms"
categories:
  - Metabolomics
description: "Peak detection tool for HRMS profile data."
long_description: "Peak detection package including (1) noise filtering, (2) peak picking, (3) retention time correction, (4) feature alignment and (5) weaker signal recovery features."
