owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/aplcms"
homepage_url: "http://web1.sph.emory.edu/apLCMS/"
categories:
  - Metabolomics
repositories:
  aplcms_unsupervised:
    description: "Generate a feature table from a batch of LC/MS spectra using apLCMS's Unsupervised method."
    include:
      - aplcms_unsupervised.xml
      - aplcms_macros.xml
      - test-data
  aplcms_hybrid:
    description: "Generate a feature table from a batch of LC/MS spectra using apLCMS's Hybrid method."
    include:
      - aplcms_hybrid.xml
      - aplcms_macros.xml
      - test-data
