name: waveica
owner: recetox
description: Batch correction tool for chromatography-mass spectrometry analysis
long_description: Removal of batch effects for large-scale untargeted metabolomics data based on wavelet analysis.
homepage_url: "https://github.com/dengkuistat/WaveICA/"
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/waveica"
Categories:
  - Metabolomics
type: unrestricted