owner: recetox
repositories:
  waveica:
    description: Removal of batch effects for untargeted metabolomics data.
    include:
      - waveica.xml
      - waveica_macros.xml
      - waveica_wrapper.R
      - test-data
long_description: Removal of batch effects for large-scale untargeted metabolomics data based on wavelet analysis.
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/waveica"
homepage_url: "https://github.com/RECETOX/WaveICA"
categories:
  - Metabolomics
type: unrestricted
