owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/mzml_validator"
homepage_url: "https://github.com/RECETOX/galaxytools"
categories:
  - Metabolomics
  - Proteomics
repositories:
  mzml_validator:
    description: "mzML Validator checks if mzML file validates against XML Schema Definition of HUPO Proteomics Standard Initiative."
