owner: recetox
repositories:
  xtb_molecular_optimization:
    description:  data.
    include:
      - xtb.xml
      - test-data
long_description:  analysis.
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/xtb"
homepage_url: "https://github.com/RECETOX/galaxytools"
categories:
  - Metabolomics
type: unrestricted
