owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/matchms"
homepage_url: "https://github.com/matchms/matchms"
categories:
  - Metabolomics
repositories:
  matchms:
    description: "Matchms is an open-source Python package to import, process, clean, and compare mass spectrometry data (MS/MS)."
    include:
      - matchms.xml
      - matchms_wrapper.py
      - test-data
      - macros.xml
  matchms_formatter:
    description: "Tool to reformat output tables of matchms."
    include:
      - matchms_formatter.xml
      - formatter.py
      - test-data
      - macros.xml
