owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/matchms"
homepage_url: "https://github.com/matchms/matchms"
categories:
  - Metabolomics
repositories:
  matchms:
    description: "Calculate the similarity score and matched peaks for mass spectrometry data (MS/MS)."
    include:
      - matchms_similarity.xml
      - matchms_similarity_wrapper.py
      - test-data
      - macros.xml
  matchms_filtering:
    description: "Filter and normalize mass spectrometry data (MS/MS)."
    include:
      - matchms_filtering.xml
      - matchms_filtering_wrapper.py
      - test-data/filtering
      - macros.xml
  matchms_formatter:
    description: "Tool to reformat output tables of matchms."
    include:
      - matchms_formatter.xml
      - formatter.py
      - test-data
      - macros.xml
  matchms_networking:
    description: "Create a similarity network graph from spectral similarity scores."
    include:
      - matchms_networking.xml
      - matchms_networking_wrapper.py
      - test-data
      - macros.xml
  matchms_convert:
    description: "Convert between mass spectral library formats using matchms."
    include:
      - matchms_convert.xml
      - test-data
      - macros.xml
  matchms_split:
    description: "Utility tool to split an `msp` file into chunks of records."
    include:
      - matchms_split.xml
      - matchms_split.py
      - test-data
      - macros.xml
  matchms_metadata_export:
    description: "Export all metadata from mass spectra file to tabular format."
    include:
      - matchms_extract_metadata.xml
      - test-data
      - macros.xml
