name: matchms
owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/matchms"
homepage_url: "https://github.com/matchms/matchms"
categories:
  - Metabolomics
description: "Searching, filtering and converting mass spectral libraries."
long_description: "Tools to filter (normalize intensities, filter mz range, convert adducts, ...) and convert (msp/mgf/json) mass spectral libraries and to perform spectral, fingerprint and metadata similarity calculations as well as molecular networking."
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the matchms package"
suite:
  name: suite_matchms
  description: tools from the matchms suite are used for filtering, converting and searching mass spectral libraries and molecular networking
  type: repository_suite_definition