owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/xmsannotator"
homepage_url: "https://github.com/kuppal2/xMSannotator"
categories:
  - Metabolomics
repositories:
  xmsannotator_simple:
    description: "Annotate peak table with metabolites"
    include:
      - xmsannotator_simple.xml
      - xmsannotator_macros.xml
      - tool_data_table_conf.xml.sample
      - tool-data/metabolite_databases.loc.sample
  xmsannotator_advanced:
    description: "Annotate peak table with metabolites"
    include:
      - xmsannotator_advanced.xml
      - xmsannotator_macros.xml
      - tool_data_table_conf.xml.sample
      - tool-data/metabolite_databases.loc.sample
